# Generated by Django 4.2.14 on 2024-07-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MayBienAp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('vi_tri', models.CharField(max_length=100)),
                ('kinh_do', models.FloatField()),
                ('vi_do', models.FloatField()),
                ('cong_suat', models.FloatField()),
                ('uc', models.FloatField()),
                ('uh', models.FloatField()),
                ('ton_hao_khong_tai', models.FloatField()),
                ('ton_hao_ngan_mach', models.FloatField()),
                ('un_phan_tram', models.FloatField()),
                ('i0_phan_tram', models.FloatField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('su_co', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThietLapCanhBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong_canh_bao', models.FloatField(default=100)),
                ('dien_ap_thap', models.FloatField(default=210)),
                ('dien_ap_cao', models.FloatField(default=240)),
                ('may_bien_ap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MBA.maybienap')),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('trang_thai', models.BooleanField(default=False)),
                ('may_bien_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBA.maybienap')),
            ],
        ),
        migrations.CreateModel(
            name='DuLieuMayBienAp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('dien_ap_pha_a', models.FloatField()),
                ('dien_ap_pha_b', models.FloatField()),
                ('dien_ap_pha_c', models.FloatField()),
                ('dong_pha_a', models.FloatField()),
                ('dong_pha_b', models.FloatField()),
                ('dong_pha_c', models.FloatField()),
                ('cong_suat_tac_dung_a', models.FloatField()),
                ('cong_suat_tac_dung_b', models.FloatField()),
                ('cong_suat_tac_dung_c', models.FloatField()),
                ('may_bien_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBA.maybienap')),
            ],
        ),
        migrations.CreateModel(
            name='DuLieuLuuTru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('dien_ap_pha_a', models.FloatField()),
                ('dien_ap_pha_b', models.FloatField()),
                ('dien_ap_pha_c', models.FloatField()),
                ('dong_pha_a', models.FloatField()),
                ('dong_pha_b', models.FloatField()),
                ('dong_pha_c', models.FloatField()),
                ('cong_suat_tac_dung_a', models.FloatField()),
                ('cong_suat_tac_dung_b', models.FloatField()),
                ('cong_suat_tac_dung_c', models.FloatField()),
                ('may_bien_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBA.maybienap')),
            ],
        ),
        migrations.CreateModel(
            name='CanhBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('du_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBA.dulieumaybienap')),
            ],
        ),
    ]
